const ACTIONS = {
  COUNTER_INCREASE: "COUNTER_INCREASE",
  COUNTER_DECREASE: "COUNTER_DECREASE",

  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAIL: "GET_POST_FAIL",
  GET_POST_FINISH: "GET_POST_FINISH",

  GET_POST_BYID_SUCCESS: "GET_POST_BYID_SUCCESS",
};

export default ACTIONS;
